package com.example.miaosha.miaosha002.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.user_id
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.goods_id
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    private Long goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.adder_id
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    private Long adderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.goods_name
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.goods_count
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    private Integer goodsCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.goods_price
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    private BigDecimal goodsPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_channel
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    private Byte orderChannel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.status
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.create_date
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.pay_date
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    private Date payDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.user_id
     *
     * @return the value of order.user_id
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.user_id
     *
     * @param userId the value for order.user_id
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.goods_id
     *
     * @return the value of order.goods_id
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.goods_id
     *
     * @param goodsId the value for order.goods_id
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.adder_id
     *
     * @return the value of order.adder_id
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    public Long getAdderId() {
        return adderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.adder_id
     *
     * @param adderId the value for order.adder_id
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    public void setAdderId(Long adderId) {
        this.adderId = adderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.goods_name
     *
     * @return the value of order.goods_name
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.goods_name
     *
     * @param goodsName the value for order.goods_name
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.goods_count
     *
     * @return the value of order.goods_count
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    public Integer getGoodsCount() {
        return goodsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.goods_count
     *
     * @param goodsCount the value for order.goods_count
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    public void setGoodsCount(Integer goodsCount) {
        this.goodsCount = goodsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.goods_price
     *
     * @return the value of order.goods_price
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    public BigDecimal getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.goods_price
     *
     * @param goodsPrice the value for order.goods_price
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    public void setGoodsPrice(BigDecimal goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_channel
     *
     * @return the value of order.order_channel
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    public Byte getOrderChannel() {
        return orderChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_channel
     *
     * @param orderChannel the value for order.order_channel
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    public void setOrderChannel(Byte orderChannel) {
        this.orderChannel = orderChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.status
     *
     * @return the value of order.status
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.status
     *
     * @param status the value for order.status
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.create_date
     *
     * @return the value of order.create_date
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.create_date
     *
     * @param createDate the value for order.create_date
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.pay_date
     *
     * @return the value of order.pay_date
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    public Date getPayDate() {
        return payDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.pay_date
     *
     * @param payDate the value for order.pay_date
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    public void setPayDate(Date payDate) {
        this.payDate = payDate;
    }
}