package com.example.miaosha.miaosha002.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Seckill {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.id
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.goods_id
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    private Long goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.price
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.count
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.start_date
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.end_date
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    private Date endDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.id
     *
     * @return the value of seckill.id
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.id
     *
     * @param id the value for seckill.id
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.goods_id
     *
     * @return the value of seckill.goods_id
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.goods_id
     *
     * @param goodsId the value for seckill.goods_id
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.price
     *
     * @return the value of seckill.price
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.price
     *
     * @param price the value for seckill.price
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.count
     *
     * @return the value of seckill.count
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.count
     *
     * @param count the value for seckill.count
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.start_date
     *
     * @return the value of seckill.start_date
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.start_date
     *
     * @param startDate the value for seckill.start_date
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.end_date
     *
     * @return the value of seckill.end_date
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.end_date
     *
     * @param endDate the value for seckill.end_date
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
}