package com.example.miaosha.miaosha001.dataobject;

public class StockDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.id
     *
     * @mbg.generated Mon Dec 06 22:32:57 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.name
     *
     * @mbg.generated Mon Dec 06 22:32:57 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.count
     *
     * @mbg.generated Mon Dec 06 22:32:57 CST 2021
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.sale
     *
     * @mbg.generated Mon Dec 06 22:32:57 CST 2021
     */
    private Integer sale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.version
     *
     * @mbg.generated Mon Dec 06 22:32:57 CST 2021
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.id
     *
     * @return the value of stock.id
     *
     * @mbg.generated Mon Dec 06 22:32:57 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.id
     *
     * @param id the value for stock.id
     *
     * @mbg.generated Mon Dec 06 22:32:57 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.name
     *
     * @return the value of stock.name
     *
     * @mbg.generated Mon Dec 06 22:32:57 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.name
     *
     * @param name the value for stock.name
     *
     * @mbg.generated Mon Dec 06 22:32:57 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.count
     *
     * @return the value of stock.count
     *
     * @mbg.generated Mon Dec 06 22:32:57 CST 2021
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.count
     *
     * @param count the value for stock.count
     *
     * @mbg.generated Mon Dec 06 22:32:57 CST 2021
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.sale
     *
     * @return the value of stock.sale
     *
     * @mbg.generated Mon Dec 06 22:32:57 CST 2021
     */
    public Integer getSale() {
        return sale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.sale
     *
     * @param sale the value for stock.sale
     *
     * @mbg.generated Mon Dec 06 22:32:57 CST 2021
     */
    public void setSale(Integer sale) {
        this.sale = sale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.version
     *
     * @return the value of stock.version
     *
     * @mbg.generated Mon Dec 06 22:32:57 CST 2021
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.version
     *
     * @param version the value for stock.version
     *
     * @mbg.generated Mon Dec 06 22:32:57 CST 2021
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}