package com.example.miaosha.miaosha001.dao;

import com.example.miaosha.miaosha001.dataobject.StockDo;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface StockDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbg.generated Mon Dec 06 22:32:57 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbg.generated Mon Dec 06 22:32:57 CST 2021
     */
    int insert(StockDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbg.generated Mon Dec 06 22:32:57 CST 2021
     */
    int insertSelective(StockDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbg.generated Mon Dec 06 22:32:57 CST 2021
     */
    StockDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbg.generated Mon Dec 06 22:32:57 CST 2021
     */
    int updateByPrimaryKeySelective(StockDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbg.generated Mon Dec 06 22:32:57 CST 2021
     */
    int updateByPrimaryKey(StockDo record);

    /**
     * 通过乐观锁更新库存
     * @param stockDo
     * @return
     */
    int updateByoptimisetic(StockDo stockDo);
}