package com.example.miaosha.miaosha001.dao;

import com.example.miaosha.miaosha001.dataobject.UserInfoDao;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface UserInfoDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Mon Dec 06 22:32:57 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Mon Dec 06 22:32:57 CST 2021
     */
    int insert(UserInfoDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Mon Dec 06 22:32:57 CST 2021
     */
    int insertSelective(UserInfoDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Mon Dec 06 22:32:57 CST 2021
     */
    UserInfoDao selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Mon Dec 06 22:32:57 CST 2021
     */
    int updateByPrimaryKeySelective(UserInfoDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Mon Dec 06 22:32:57 CST 2021
     */
    int updateByPrimaryKey(UserInfoDao record);
}