package com.example.miaosha.miaosha002.dao;

import com.example.miaosha.miaosha002.entity.Seckill;

public interface SeckillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    int insert(Seckill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    int insertSelective(Seckill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    Seckill selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    int updateByPrimaryKeySelective(Seckill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbg.generated Thu Dec 23 20:41:02 CST 2021
     */
    int updateByPrimaryKey(Seckill record);
}